version: '3.9'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=tim
      - POSTGRES_PASSWORD=tim
      - POSTGRES_DB=todo_db
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgresql/data

#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: always
#    env_file:
#      - ./.env
#    environment:
#      POSTGRES_HOST: postgres
#    depends_on:
#      postgres:
#        condition: service_healthy