# Generated by Django 4.1.2 on 2022-11-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_user_change_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='change_sex',
        ),
    ]
