# Generated by Django 4.1.2 on 2022-11-10 15:40

from django.db import migrations, transaction
from django.utils import timezone


def create_objects(apps, schema_editors):
    User = apps.get_model("core", "User")
    Board = apps.get_model("goals", "Board")
    BoardParticipant = apps.get_model("goals", "BoardParticipant")
    GoalCategory = apps.get_model("goals", "GoalCategory")

    with transaction.atomic():
        now = timezone.now()
        for user_id in User.objects.values_list("id", flat=True):
            new_board = Board.objects.create(title="Мои Цели", created=now, updated=now)
            BoardParticipant.objects.create(user_id=user_id, board=new_board, role=1, created=now, updated=now)
            GoalCategory.objects.filter(user_id=user_id).update(board=new_board)


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_board_alter_goalcomment_user_goalcategory_board_and_more'),
    ]

    operations = [
        migrations.RunPython(create_objects)
    ]
