version: '3.8'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      timeout: 5s
      interval: 5s
      retries: 3


  api:
    build:
      context: .
    restart: always
    environment:
      DB_HOST: postgres
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./src:/opt/todolist

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    depends_on:
      - postgres
      - api
    ports:
      - '80:80'
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf