version: '3.9'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data/:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}' ]
      timeout: 5s
      interval: 5s
      retries: 3


  api:
    image: ${DOCKERHUB_USERNAME}/diplom:latest
    restart: always
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: sermalenk/skypro-front:lesson-35
    restart: always
    depends_on:
      - postgres
      - api
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/opt/static

volumes:
  pg_data: